<!-- generated by Dynamator Sat Jan 31 15:07:24 CST 2004 --><xsl:stylesheet
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	version="1.1" >

<xsl:output method="text"/>
<xsl:template match="/type"><xsl:text>
</xsl:text><a-replaced/><xsl:text> </xsl:text><b-replaced/><xsl:text>
</xsl:text><a-replaced/><xsl:text> </xsl:text><xsl:if test="some-condition"><b-replaced/></xsl:if>

public
class X
implements<xsl:text>
    </xsl:text><xsl:if test="@serializable">Serializable</xsl:if><xsl:text>
    </xsl:text><xsl:if test="@cloneable">Cloneable</xsl:if>
{
}

public
class X
implements<xsl:text>
    </xsl:text><xsl:if test="@cloneable">Cloneable</xsl:if><xsl:text>
    </xsl:text><xsl:if test="@serializable">Serializable</xsl:if>
{
}<xsl:text>
</xsl:text></xsl:template>
</xsl:stylesheet>
