<!-- generated by Dynamator Sat Jan 31 15:07:24 CST 2004 --><xsl:stylesheet
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	version="1.1" >

<xsl:output method="text"/>
<xsl:template match="/type"><xsl:text>
</xsl:text><xsl:choose><xsl:when test="'1'='1'"></xsl:when><xsl:otherwise></xsl:otherwise></xsl:choose><xsl:text>
</xsl:text></xsl:template>
</xsl:stylesheet>
