<%-- generated by Dynamator Sat Aug 07 13:07:36 CDT 2004
--%><html>
  <head>
    <title>Test Bug 1003120</title>
  </head>
  <body>
    <html:img page="/test.png"></html:img> <html:img page="/test.png"></html:img>
  </body>
</html>
