<%-- generated by Dynamator Sat Oct 26 21:53:32 CDT 2002
--%>
    <%@ page session="false" %>
    <%!
        public
        String
        getGreeting()
        {
            return "Hello World, says Dynamator!";
        }
    
        public
        String
        getTextColor()
        {
            return "#cc00cc";
        }
    
        public
        String
        getParagraphAlignment()
        {
            return "center";
        }
    %>
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Hello World</title>
  </head>
  <body>
    <p id="DynamicText" align="<%= getParagraphAlignment() %>"><font id="DynamicFont" color="<%= getTextColor() %>"><%= getGreeting() %></font></p>
  </body>
</html>
