<%-- generated by Dynamator Sun Jul 18 17:35:59 CDT 2004
--%><html>
  <head>
    <title></title>
  </head>
  <body>
    <table>
      <tr><!-- div id="div-id" class="y" --><%
          for ( int i=1; i < 10; ++i )
          {
        %>
            <td>data line 1</td>
            <td><img src="line.png" height="1" width="100"></td>
<%
          }  // for
        %><!-- /div -->
      </tr>
    </table>
    <table>
      <tr><%
          for ( int j=1; j < 10; ++j )
          {
        %>
            <td>data line 2</td>
            <td><img src="line.png" height="1" width="100"></td>
<%
          }  // for
        %>
      </tr>
    </table>
    <p>No comment div should surround this text.</p>
    <!-- div id="replace-content" --><%= 
    <%= "Content replaced" %>
   %><!-- /div -->
  </body>
</html>
