<%-- generated by Dynamator Sun Feb 15 17:32:58 CST 2004
--%>
    <%@ page session="false" %>
    <%!
        private static final String[] colors_ = 
            new String[]
            {
                "red",
                "orange",
                "green",
                "brown",
                "slate",
            };
    %> 
    <%
        String likeInput = request.getParameter("like");
        int like = 
            ( likeInput == null || likeInput.length() == 0 )
            ? -1
            : Integer.valueOf(likeInput).intValue();
    %>
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Favorite Color</title>
  </head>
  <body>
    <form>
      <p>Which color is your favorite? <select name="like">
          <option value="-1"></option>
<%
            {
              String[] $colors_ = colors_;
              int lim$colors_ = $colors_.length;
              String color;
              for ( int iColor = 0; iColor < lim$colors_; ++iColor )
              {
                color = $colors_[iColor];
          %><option id="color" value="<%= iColor %>"<%
                  if ( iColor == like ) 
                  {
                    %> selected<%
                  }
                %>><%= color %></option><%
              }
            }
          %>
        </select></p>
      <p><input type="SUBMIT"></p>
    </form>
  </body>
</html>
