<%-- generated by Dynamator Sun Feb 15 17:32:58 CST 2004
--%>
    <%@ page session="false" %>
    <%
        ThreadGroup tg = Thread.currentThread().getThreadGroup();

        Thread[] threads = new Thread[tg.activeCount()];
        int n = tg.enumerate(threads);

        if ( n < threads.length )
        {
            Thread[] newThreads = new Thread[n];
            System.arraycopy(threads, 0, newThreads, 0, n);
            threads = newThreads;
        }
    %>
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Currently Executing Threads</title>
  </head>
  <body bgcolor="khaki">
    <table border="1">
      <tr id="th" align="center"<%= " bgcolor=\"#eeeeee\"" %>>
        <td>Name</td>
        <td>Priority</td>
        <td>Daemon?</td>
        <td>Alive?</td>
        <td>Running?</td>
      </tr>

      <% /* before */ %>
    <%
        if ( 1 == 1 ) 
        {
          %><%
            {
              Thread[] $threads = threads;
              int lim$threads = $threads.length;
              Thread thread;
              for ( int iThreads = 0; iThreads < lim$threads; ++iThreads )
              {
                thread = $threads[iThreads];
          %><tr align="center">
      <% /* before Content */ %>
    <td id="name"><%= thread.getName() %></td>
                  <td id="priority"><%= thread.getPriority() %></td>
                  <td><%
                      if ( thread.isDaemon() ) 
                      {
                        %><span id="isDaemon">Y</span><%
                      }
                    %> <%
                      if ( !thread.isDaemon() ) 
                      {
                        %><span id="isNotDaemon">&nbsp;</span><%
                      }
                    %> </td>
                  <td><%
                      if ( thread.isAlive() ) 
                      {
                        %><span id="isAlive">Y</span><%
                      }
                    %> <%
                      if ( !thread.isAlive() ) 
                      {
                        %><span id="isNotAlive">&nbsp;</span><%
                      }
                    %> </td>
                  <td><%
                      if ( thread.isInterrupted() ) 
                      {
                        %><span id="isInterrupted">&nbsp;</span><%
                      }
                    %> <%
                      if ( !thread.isInterrupted() ) 
                      {
                        %><span id="isNotInterrupted">Y</span><%
                      }
                    %> </td>

      <% /* after Content */ %>
                    </tr><%
              }
            }
          %><%
        }
      %>
      <% /* after */ %>
    </table>
  </body>
</html>
