<%-- generated by Dynamator Sun Feb 15 17:32:58 CST 2004
--%>
    <%@ page session="false" %>
    <%@ page import="java.util.Vector" %>
    <%
        Vector v = new Vector();
        v.addElement("a");
        v.addElement("b");
        v.addElement("c");
        v.addElement("d");
    %>
  <html>
  <head>
    <title></title>
  </head>
  <body>
<%
      {
        java.util.Locale[] $javaUtilLocaleAvailableLocales = java.util.Locale.getAvailableLocales();
        int lim$javaUtilLocaleAvailableLocales = $javaUtilLocaleAvailableLocales.length;
        java.util.Locale locale;
        for ( int i$javaUtilLocaleAvailableLocales = 0; i$javaUtilLocaleAvailableLocales < lim$javaUtilLocaleAvailableLocales; ++i$javaUtilLocaleAvailableLocales )
        {
          locale = $javaUtilLocaleAvailableLocales[i$javaUtilLocaleAvailableLocales];
    %><p id="Array1"><%= locale %></p><%
        }
      }
    %>
<%
      {
        java.util.Locale[] $javaUtilLocaleAvailableLocales = java.util.Locale.getAvailableLocales();
        int lim$javaUtilLocaleAvailableLocales = $javaUtilLocaleAvailableLocales.length;
        java.util.Locale locale;
        for ( int iLocale = 0; iLocale < lim$javaUtilLocaleAvailableLocales; ++iLocale )
        {
          locale = $javaUtilLocaleAvailableLocales[iLocale];
    %><p id="Array2"><%= locale %></p><%
        }
      }
    %>
<%
      {
        java.util.Locale[] locales = java.util.Locale.getAvailableLocales();
        int limLocales = locales.length;
        java.util.Locale locale;
        for ( int iLocale = 0; iLocale < limLocales; ++iLocale )
        {
          locale = locales[iLocale];
    %><p id="Array3"><%= locale %></p><%
        }
      }
    %>
<%
      {
        java.util.Vector $v = v;
        int lim$v = $v.size();
        String item;
        for ( int i$v = 0; i$v < lim$v; ++i$v )
        {
          item = (String) $v.elementAt(i$v);
    %><p id="Vector1"><%= item %></p><%
        }
      }
    %>
<%
      {
        java.util.Vector $v = v;
        int lim$v = $v.size();
        String item;
        for ( int iItem = 0; iItem < lim$v; ++iItem )
        {
          item = (String) $v.elementAt(iItem);
    %><p id="Vector2"><%= item %></p><%
        }
      }
    %>
<%
      {
        java.util.Vector items = v;
        int limItems = items.size();
        String item;
        for ( int iItem = 0; iItem < limItems; ++iItem )
        {
          item = (String) items.elementAt(iItem);
    %><p id="Vector3"><%= item %></p><%
        }
      }
    %>
<%
      {
        java.util.Enumeration $systemPropertiesPropertyNames = System.getProperties().propertyNames();
        String name;
        while ( $systemPropertiesPropertyNames.hasMoreElements() )
        {
          name = (String) $systemPropertiesPropertyNames.nextElement();
    %><p id="Enumeration1"><%= name %></p><%
        }
      }
    %>
<%
      {
        java.util.Enumeration $systemPropertiesPropertyNames = System.getProperties().propertyNames();
        String name;
        int iName = -1;
        while ( $systemPropertiesPropertyNames.hasMoreElements() )
        {
          name = (String) $systemPropertiesPropertyNames.nextElement();
          ++iName;
    %><p id="Enumeration2"><%= name %></p><%
        }
      }
    %>
<%
      {
        java.util.Enumeration names = System.getProperties().propertyNames();
        String name;
        int iName = -1;
        while ( names.hasMoreElements() )
        {
          name = (String) names.nextElement();
          ++iName;
    %><p id="Enumeration3"><%= name %></p><%
        }
      }
    %>
<%
      {
        java.util.Iterator $systemPropertiesPropertyNames = System.getProperties().propertyNames();
        String name;
        while ( $systemPropertiesPropertyNames.hasNext() )
        {
          name = (String) $systemPropertiesPropertyNames.next();
    %><p id="Iterator1"><%= name %></p><%
        }
      }
    %>
<%
      {
        java.util.Iterator $systemPropertiesPropertyNames = System.getProperties().propertyNames();
        String name;
        int iName = -1;
        while ( $systemPropertiesPropertyNames.hasNext() )
        {
          name = (String) $systemPropertiesPropertyNames.next();
          ++iName;
    %><p id="Iterator2"><%= name %></p><%
        }
      }
    %>
<%
      {
        java.util.Iterator names = System.getProperties().propertyNames();
        String name;
        int iName = -1;
        while ( names.hasNext() )
        {
          name = (String) names.next();
          ++iName;
    %><p id="Iterator3"><%= name %></p><%
        }
      }
    %>
<%
      {
        java.util.Dictionary $systemProperties = System.getProperties();
        String property;
        String propertyKey;
        java.util.Enumeration $systemPropertiesKeys = $systemProperties.keys();
        while ( $systemPropertiesKeys.hasMoreElements() )
        {
          propertyKey = (String) $systemPropertiesKeys.nextElement();
          property = (String) $systemProperties.get(propertyKey);
    %><p id="Dictionary1"><%= property %></p><%
        }
      }
    %>
<%
      {
        java.util.Dictionary $systemProperties = System.getProperties();
        String property;
        String propertyKey;
        java.util.Enumeration $systemPropertiesKeys = $systemProperties.keys();
        int iProperty = -1;
        while ( $systemPropertiesKeys.hasMoreElements() )
        {
          propertyKey = (String) $systemPropertiesKeys.nextElement();
          property = (String) $systemProperties.get(propertyKey);
          ++iProperty;
    %><p id="Dictionary2"><%= property %></p><%
        }
      }
    %>
<%
      {
        java.util.Dictionary d = System.getProperties();
        String property;
        String propertyKey;
        java.util.Enumeration dKeys = d.keys();
        int iProperty = -1;
        while ( dKeys.hasMoreElements() )
        {
          propertyKey = (String) dKeys.nextElement();
          property = (String) d.get(propertyKey);
          ++iProperty;
    %><p id="Dictionary3"><%= property %></p><%
        }
      }
    %>
<%
      {
        java.util.Map $systemProperties = System.getProperties();
        java.util.Map.Entry property;
        String propertyKey;
        String propertyValue;
        java.util.Iterator $systemPropertiesEntries = $systemProperties.entrySet().iterator();
        while ( $systemPropertiesEntries.hasNext() )
        {
          property = (java.util.Map.Entry) $systemPropertiesEntries.next();
          propertyKey = (String) property.getKey();
          propertyValue = (String) property.getValue();
    %><p id="Map1"><%= property %></p><%
        }
      }
    %>
<%
      {
        java.util.Map $systemProperties = System.getProperties();
        java.util.Map.Entry property;
        String propertyKey;
        String propertyValue;
        java.util.Iterator $systemPropertiesEntries = $systemProperties.entrySet().iterator();
        int iProperty = -1;
        while ( $systemPropertiesEntries.hasNext() )
        {
          property = (java.util.Map.Entry) $systemPropertiesEntries.next();
          propertyKey = (String) property.getKey();
          propertyValue = (String) property.getValue();
          ++iProperty;
    %><p id="Map2"><%= property %></p><%
        }
      }
    %>
<%
      {
        java.util.Map d = System.getProperties();
        java.util.Map.Entry property;
        String propertyKey;
        String propertyValue;
        java.util.Iterator dEntries = d.entrySet().iterator();
        int iProperty = -1;
        while ( dEntries.hasNext() )
        {
          property = (java.util.Map.Entry) dEntries.next();
          propertyKey = (String) property.getKey();
          propertyValue = (String) property.getValue();
          ++iProperty;
    %><p id="Map3"><%= property %></p><%
        }
      }
    %>
<%
      {
        java.util.Properties $systemProperties = System.getProperties();
        String property;
        String propertyName;
        java.util.Enumeration $systemPropertiesNames = $systemProperties.propertyNames();
        while ( $systemPropertiesNames.hasMoreElements() )
        {
          propertyName = (String) $systemPropertiesNames.nextElement();
          property = $systemProperties.getProperty(propertyName);
    %><p id="Properties1"><%= property %></p><%
        }
      }
    %>
<%
      {
        java.util.Properties $systemProperties = System.getProperties();
        String property;
        String propertyName;
        java.util.Enumeration $systemPropertiesNames = $systemProperties.propertyNames();
        int iProperty = -1;
        while ( $systemPropertiesNames.hasMoreElements() )
        {
          propertyName = (String) $systemPropertiesNames.nextElement();
          property = $systemProperties.getProperty(propertyName);
          ++iProperty;
    %><p id="Properties2"><%= property %></p><%
        }
      }
    %>
<%
      {
        java.util.Properties properties = System.getProperties();
        String property;
        String propertyName;
        java.util.Enumeration propertiesNames = properties.propertyNames();
        int iProperty = -1;
        while ( propertiesNames.hasMoreElements() )
        {
          propertyName = (String) propertiesNames.nextElement();
          property = properties.getProperty(propertyName);
          ++iProperty;
    %><p id="Properties3"><%= property %></p><%
        }
      }
    %>
  </body>
</html>
