<%-- generated by Dynamator Sun Feb 15 17:32:58 CST 2004
--%><html>
  <head>
    <title></title>
  </head>
  <body>
    <dl><%
        {
          java.util.Properties $systemProperties = System.getProperties();
          String property;
          String propertyName;
          java.util.Enumeration $systemPropertiesNames = $systemProperties.propertyNames();
          while ( $systemPropertiesNames.hasMoreElements() )
          {
            propertyName = (String) $systemPropertiesNames.nextElement();
            property = $systemProperties.getProperty(propertyName);
      %><%
              if ( ! "java.class.path".equals(propertyName) ) 
              {
            %>
                <dt class="name"><%= propertyName %></dt>
                <dd class="value"><%= property %></dd>
<%
              }
            %><%
          }
        }
      %></dl>
    <table>
<%
        {
          java.util.Properties $systemProperties = System.getProperties();
          String property;
          String propertyName;
          java.util.Enumeration $systemPropertiesNames = $systemProperties.propertyNames();
          while ( $systemPropertiesNames.hasMoreElements() )
          {
            propertyName = (String) $systemPropertiesNames.nextElement();
            property = $systemProperties.getProperty(propertyName);
      %><%
              if ( ! "java.class.path".equals(propertyName) ) 
              {
            %><tr>
                  <td class="name"><%= propertyName %></td>
                  <td class="value"><%= property %></td>
                </tr><%
              }
            %><%
          }
        }
      %>
    </table>
<%
      {
        java.util.Properties $systemProperties = System.getProperties();
        String property;
        String propertyName;
        java.util.Enumeration $systemPropertiesNames = $systemProperties.propertyNames();
        while ( $systemPropertiesNames.hasMoreElements() )
        {
          propertyName = (String) $systemPropertiesNames.nextElement();
          property = $systemProperties.getProperty(propertyName);
    %><%
            if ( ! "java.class.path".equals(propertyName) ) 
            {
          %><p class="1"><span class="name"><%= propertyName %></span>:<span class="value"><%= property %></span></p><%
            }
          %><%
        }
      }
    %>
before<%
      if ( true ) 
      {
        %><%
          {
            java.util.Properties $systemProperties = System.getProperties();
            String property;
            String propertyName;
            java.util.Enumeration $systemPropertiesNames = $systemProperties.propertyNames();
            while ( $systemPropertiesNames.hasMoreElements() )
            {
              propertyName = (String) $systemPropertiesNames.nextElement();
              property = $systemProperties.getProperty(propertyName);
        %><%
                if ( ! "java.class.path".equals(propertyName) ) 
                {
              %><p class="2">before-content<span class="name"><%= propertyName %></span>:<span class="value"><%= property %></span>after-content</p><%
                }
              %><%
            }
          }
        %><%
      }
    %>after</body>
</html>
