<%-- generated by Dynamator Sat Jul 26 15:26:54 CDT 2003
--%>
    <%@ page session="false" %>
    <jsp:useBean id="subject" class="Dynamator_tutorial.HelloWorldBean" />
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Hello World</title>
  </head>
  <body>
    <p id="DynamicText"><jsp:getProperty name="subject" property="greeting"/></p>
  </body>
</html>
