<%-- generated by Dynamator Sun Feb 15 17:32:58 CST 2004
--%>
    <%@ page session="false" %>
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>System Properties</title>
  </head>
  <body>
    <dl id="Properties"><%
        {
          java.util.Properties $systemProperties = System.getProperties();
          String property;
          String propertyName;
          java.util.Enumeration $systemPropertiesNames = $systemProperties.propertyNames();
          while ( $systemPropertiesNames.hasMoreElements() )
          {
            propertyName = (String) $systemPropertiesNames.nextElement();
            property = $systemProperties.getProperty(propertyName);
      %>
            <dt id="PropertyName"><%= propertyName %></dt>
            <dd id="PropertyValue"><%= property %></dd>
<%
          }
        }
      %></dl>
  </body>
</html>
