<%-- generated by Dynamator Sun Feb 15 17:32:58 CST 2004
--%>
<%!
    private static
    class Element
    {
        private String name_;
        private Element[] children_ = {};
        
        public
        Element(
            String name
            )
        {
            name_ = name;
        }

        public
        Element(
            String name,
            Element[] children
            )
        {
            name_ = name;
            children_ = children;
        }

        public
        String
        name()
        {
            return name_;
        }
        
        public
        Element[] 
        children()
        {
            return children_;
        }
    }

    private static Element root = 
        new Element("Animals",
            new Element[]
            {
                new Element("Vertebrates",
                    new Element[]
                    {
                        new Element("Warm-blooded",
                            new Element[]
                            {
                                new Element("Mammals"),
                                new Element("Birds")
                            }
                        ),
                        new Element("Cold-blooded",
                            new Element[]
                            {
                                new Element("Fish"),
                                new Element("Reptiles")
                            }
                        )
                    }
                ),
                new Element("Invertebrates",
                    new Element[]
                    {
                        new Element("Arthropods",
                            new Element[]
                            {
                                new Element("Crustaceans"),
                                new Element("Insects")
                            }
                        )
                    }
                )
            }
        );
    
    private static
    interface ElementOutputter
    {
        void
        output(
            JspWriter out,
            Element element
            )
        throws java.io.IOException;
    }
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Taxonomy</title>
  </head>
  <body>
    <h1 id="title"><%= 
      "An Informal Taxonomy of the Animal Kingdom"
     %></h1>
    <p id="root"><%= 
      root.name()
     %></p>

<%
    ElementOutputter elementOutputter = new ElementOutputter()
    {
        public
        void
        output(
            JspWriter out,
            Element element
            )
        throws java.io.IOException
        {
%>
        <ul class="children-list">
<%
        {
          Element[] $elementChildren = element.children();
          int lim$elementChildren = $elementChildren.length;
          Element child;
          for ( int i$elementChildren = 0; i$elementChildren < lim$elementChildren; ++i$elementChildren )
          {
            child = $elementChildren[i$elementChildren];
      %><li class="child"><span class="child-name"><%= 
      child.name()
     %></span> 

<%
      if ( child.children().length > 0 )
      {
          output(out, child);
      }
%>
                </li><%
          }
        }
      %>
    </ul>
<%
        }
    };
    elementOutputter.output(out, root);
%>
    </body>
</html>
