<%-- generated by Dynamator Sun Mar 07 23:41:34 CST 2004
--%><%@ page session="false" 
%><%@ page contentType="text/plain" 
%><%@ page import="java.util.Hashtable"
%><%!
    private static final Hashtable dictionary = new Hashtable();
    
    static
    {
        dictionary.put(
            "marker",
            "An invisible HTML element or attribute that identifies a "
            + "location in an HTML file.  The HTML 4.0 markers are "
            + "div, span, id, and class.");
        dictionary.put(
            "locator",
            "An element in a Dynamator annotations file that identifies "
            + "the set of elements to which a set of overrides will apply.");
        dictionary.put(
            "prolog",
            "The beginning of the generated file, before the template.");
        dictionary.put(
            "epilog",
            "The end of the generated file, after the template.");
        dictionary.put(
            "override",
            "An element in a Dynamator annotations file that specifies "
            + "a set of changes to be applied to the template.  "
            + "(AKA \"modifier\")");
        dictionary.put(
            "template",
            "The file containing the static text pattern to be output "
            + " by the generated program. ");
    }
%><?xml version="1.0"?><terms>
<%
    {
      java.util.Dictionary $dictionary = dictionary;
      String entry;
      String entryKey;
      java.util.Enumeration $dictionaryKeys = $dictionary.keys();
      while ( $dictionaryKeys.hasMoreElements() )
      {
        entryKey = (String) $dictionaryKeys.nextElement();
        entry = (String) $dictionary.get(entryKey);
  %><term name="<%= entryKey %>"><%= 
      entry
     %></term><%
      }
    }
  %>
</terms>
