<%-- generated by Dynamator Sun Feb 15 17:32:58 CST 2004
--%>
    <%@ page session="false" %>
    <%
        String textInput = request.getParameter("TextInput");
        if ( textInput == null )
        {
            textInput = "";
        }
    %>
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Dynamator Text Echo Example</title>
  </head>
  <body>
    <hr>
    <form method="GET">
      <center>
        <p>Enter text here: <input type="TEXT" name="TextInput" id="TextInputField" value="<%= textInput %>" maxlength="500" size="50"></p>
        <input type="SUBMIT" value="Display Text"> 
        <hr>
        <b id="TextInputDisplay"><%= textInput %></b></center>
    </form>
  </body>
</html>
