<%-- generated by Dynamator Sun Feb 15 17:32:58 CST 2004
--%>
    <%@ page session="false" %>
    <%
        String textInput = request.getParameter("TextInput");
        if ( textInput == null )
        {
            textInput = "";
        }
    %>
  <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Dynamator Enhanced Text Echo Example</title>
    <script type="text/javascript">
    var previousValue = "<%= textInput %>";
    function validate(form)
    {
        if ( form.elements["TextInput"].value == previousValue )
        {
            alert("You just entered that value. "
                + "Please try to be more creative.");
            return false;
        }
        return true;
    }
  
</script>
  </head>
  <body>
    <hr>
    <form method="GET">
      <center>
        <p>Please enter some new text: <input type="TEXT" name="TextInput" id="TextInputField" value="<%= textInput %>" maxlength="500" size="50"></p>
        <input type="SUBMIT" value="Display Text" onclick="validate(this.form)"> 
        <hr>
        <table>
          <tr>
            <td>
              <pre>
<%= textInput %>
</pre>
            </td>
          </tr>
        </table>
      </center>
    </form>
  </body>
</html>
