<%-- generated by Dynamator Sun Feb 15 17:32:58 CST 2004
--%>
    <%@ page session="false" %>
    <%
        int max = 10;
        String sMax = request.getParameter("max");
        if ( sMax != null && sMax.length() >= 0 )
        {
            // ignore possible NumberFormatException for this demo
            max = Integer.valueOf(sMax).intValue();
        }
    %>
  <html>
  <head>
    <title>Times Table</title>
  </head>
  <body>
    <table border="1">
      <tr>
        <td>&nbsp;</td>
<%
          for ( int x = 1; x <= max; ++x )
          {
        %><td class="x"><%= x %></td><%
          }  // for
        %>
      </tr>
<%
        for ( int y = 1; y <= max; ++y )
        {
      %><tr class="yrow">
            <td class="y"><%= y %></td>
<%
              for ( int x = 1; x <= max; ++x )
              {
            %><td class="result"><%= x * y %></td><%
              }  // for
            %>
          </tr><%
        }  // for
      %>
    </table>
  </body>
</html>
