<%-- generated by Dynamator Sun Feb 15 17:32:58 CST 2004
--%>
    <%@ page session="false" %>
    <%
        int max = 10;
        String sMax = request.getParameter("max");
        if ( sMax != null && sMax.length() >= 0 )
        {
            // ignore possible NumberFormatException for this demo
            max = Integer.valueOf(sMax).intValue();
        }
        Integer[] a = new Integer[max];
        int i = 0;
        while ( ++i <= max )
        {
            a[i-1] = new Integer(i);
        }
    %>
  <html>
  <head>
    <title>Times Table</title>
  </head>
  <body>
    <table border="1">
      <tr>
        <td>&nbsp;</td>
<%
          {
            Integer[] xAxis = a;
            int limXAxis = xAxis.length;
            Integer x;
            for ( int iXAxis = 0; iXAxis < limXAxis; ++iXAxis )
            {
              x = xAxis[iXAxis];
        %><td class="x"><%= x %></td><%
            }
          }
        %>
      </tr>
<%
        {
          Integer[] yAxis = a;
          int limYAxis = yAxis.length;
          Integer y;
          for ( int iYAxis = 0; iYAxis < limYAxis; ++iYAxis )
          {
            y = yAxis[iYAxis];
      %><tr class="yrow">
              <td class="y"><%= y %></td>
<%
                {
                  Integer[] xAxis = a;
                  int limXAxis = xAxis.length;
                  Integer x;
                  for ( int iXAxis = 0; iXAxis < limXAxis; ++iXAxis )
                  {
                    x = xAxis[iXAxis];
              %><td class="result"><%= x.intValue() * y.intValue() %></td><%
                  }
                }
              %>
            </tr><%
          }
        }
      %>
    </table>
  </body>
</html>
