<%-- generated by Dynamator Sun Feb 15 17:32:58 CST 2004
--%>
        <%@ page session="false" %>
        <%
            String valueArgument = request.getParameter("value");
            boolean value = 
                ( valueArgument == null )
                ? false
                : Boolean.valueOf(valueArgument).booleanValue();
        %>
      <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Dynamator Conditional Processing Example</title>
  </head>
  <body>
    <hr>
    <form id="form" action="<%= request.getServletPath() %>" method="GET">
      <p>Select the value desired: <select name="value">
          <option id="valueIsTrue" value="true"<%
            if ( value ) 
            {
              %> selected<%
            }
          %>>true</option>
          <option id="valueIsFalse" value="false"<%
            if ( ! value ) 
            {
              %> selected<%
            }
          %>>false</option>
        </select> <input type="SUBMIT"></p>
    </form>
    <hr>
<%
      if ( request.getQueryString()!=null ) 
      {
        %><div id="response">
<%
            if ( value ) 
            {
              %><p id="trueText">You are so optimistic!</p><%
            }
          %>
<%
            if ( ! value ) 
            {
              %><p id="falseText" class="HideForDemo">Don't be so negative!</p><%
            }
          %>
        </div><%
      }
    %>
  </body>
</html>
