<% ' generated by Dynamator Sat Jan 31 14:56:55 CST 2004
%>
<%@ Language=VBScript %>
<%
    ' I don't know how to implement a Dictionary in VB,
    ' so I haven't implemented the event feature.
    
    dayNames = Array("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")
    daysInMonth = Array(31, "?", 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)

    today = now
    thisDay = day(today)
    thisMonth = month(today)
    thisYear = year(today)

    displayMonth = request("month")
    if displayMonth = "" then
        displayMonth = thisMonth
    end if
    displayYear = request("year")
    if displayYear = "" then
        displayYear = thisYear
    end if

    displayMonthName = monthname(displayMonth)
    
    ' find first day of month
    firstDayOfMonth = WeekDay(displayMonth & "/1/" & displayYear)
    calendarDay = 1 - firstDayOfMonth

    ' find last day of month
    lastDayOfMonth = daysInMonth(displayMonth-1)
    if lastDayOfMonth = "?" then
        if displayYear mod 400 = 0 or ( displayYear mod 100 <> 0 and displayYear mod 4 = 0 ) then
            lastDayOfMonth = 29
        else
            lastDayOfMonth = 28
        end if 
    end if

    prevMonth = displayMonth - 1
    prevYear  = displayYear
    if prevMonth = 0 then
        prevMonth = 12
        prevYear = prevYear - 1
    end if 
    
    nextMonth = displayMonth + 1
    nextYear = displayYear
    if nextMonth > 12 then
        nextMonth = 1
        nextYear = nextYear + 1
    end if 
%>
<!--
    Calendar
    
    Calendar months have varying numbers of weeks and varying
    patterns of days (starting and ending on different days of the
    week).  Therefore the HTML markup for this example uses the notion
    of "prototypes".  This HTML demo page shows a single, real month.
    Out of the five weeks in the month, one week is selected as the
    prototype week.  Out of the 7 days in that week, one is selected as
    the prototype day.  This day shows all possible data that might be
    displayed for any given day.
    
    Each prototype is given an id.  The programmer instructs Dynamator
    to remove all non-prototype weeks and days, and uses the prototype
    ones to build the calendar at runtime.
--><html>
  <head>
    <title><%= displayMonthName & " " & displayYear %></title>
    <style type="text/css">
      a
      {
          text-decoration: none;
          color: #f9f9ee;
          font-weight: bold;
      }
      td
      {
          font-size: 10pt;
          font-family: sans-serif;
      }
      .month-header
      {
          background-color: #666666;
          color: #f9f9ee;
      }
      #month-title
      {
          background-color: #666666;
          color: #f9f9ee;
      }
      .day-header
      {
          background-color: #778899;
          color: #f9f9ee;
          text-align: center;
      }
      .weekday-name
      {
          background-color: #778899;
          color: #f9f9ee;
          text-align: center;
      }
      .other-month
      {
          background-color: #f9f9ee;
          width: 75px;
          height: 75px;
          vertical-align: top;
      }
      .this-month
      {
          background-color: #f0f0cc;
          width: 75px;
          height: 75px;
          vertical-align: top;
      }
      #today
      {
          background-color: #ffff99;
          height: 75px;
          vertical-align: top;
      }
      .event
      {
          font-size: 8pt;
      }
    </style>
  </head>
  <body>
    <table align="center" border="1" cellpadding="1" cellspacing="0">
      <tr class="month-header">
        <td colspan="7">
          <table border="0" width="100%">
            <tr>
              <td align="left"><a id="prev" href="<%= request("SCRIPT_NAME") & "?month="  & prevMonth & "&year=" & prevYear %>">&#171;</a></td>
              <td id="month-title" align="center"><%= displayMonthName & " " & displayYear %></td>
              <td align="right"><a id="next" href="<%= request("SCRIPT_NAME") & "?month="  & nextMonth & "&year=" & nextYear %>">&#187;</a></td>
            </tr>
          </table>
        </td>
      </tr>
      <tr class="day-header">
        
        <%
          For Each dayName in dayNames
        %><td class="weekday-name"><%= dayName %></td>
        <%
          Next
        %>
      </tr>

    <% Do While calendarDay < lastDayOfMonth %>
          <tr class="week">

    <%
        For dayOfWeek = 1 To 7
            calendarDay = calendarDay + 1
    
            if calendarDay = thisDay and displayMonth = thisMonth and displayYear = thisYear then
                dayId = "id=""today"""
            else
                dayId = ""
            end if
    
            if 1 <= calendarDay and calendarDay <= lastDayOfMonth then
                cellClass = "this-month"
                displayDate = calendarDay
            else
                cellClass = "other-month"
                displayDate = "&nbsp;"
            end if
    %>
            <td class="<%= cellClass %>" height="75" width="75" <%= dayId %>><%= displayDate %>
          </td>
    <%
        Next
    %>
  </tr>
    <% Loop %>
  </table>
  </body>
</html>
