<% ' generated by Dynamator Thu Oct 10 16:46:38 CDT 2002
%>
<%@ 
    Language=VBScript 
%>
<% 
    greeting = "Hello World, says Dynamator!"
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Hello World</title>
  </head>
  <body>
    <p id="DynamicText"><%= greeting %></p>
  </body>
</html>
