<% ' generated by Dynamator Sat Jan 31 14:56:55 CST 2004
%>
<%@ 
    Language=VBScript 
%>
<% 
    theHour = Hour(Now)
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>What time is it?</title>
  </head>
  <body>
    <p>The time is <span id="CurrentTime"><%= Now %></span></p>
<%
      if theHour < 12 then
        %><p id="IfMorning">Good Morning!</p><%
      end if
    %>
<%
      if 12 <= theHour and theHour < 18 then
        %><p id="IfAfternoon">Good Afternoon!</p><%
      end if
    %>
<%
      if 18 <= theHour then
        %><p id="IfEvening">Good Evening!</p><%
      end if
    %>
  </body>
</html>
