<!-- generated by Dynamator Mon Jun 25 20:44:33 CDT 2001
--><html>
  <head>
    <title>Font sizes</title>
  </head>
  <body>
    <div class="size">

      <% For i = 0 to 7 %>
          <p><font size="<%= i %>" class="font">This is font size <span class="fontsize"><%= i %></span>.</font></p>

      <% Next i %>
        </div>
  </body>
</html>
