<%-- generated by Dynamator Sun Feb 15 17:30:05 CST 2004
--%><html>
  <head>
    <title>Attribute References</title>
  </head>
  <body>
    <a href="x.htm">should be x.htm</a> <br>
    <a href="x.htm">should be x.htm</a> <br>
    <a href="x.htm#x">should be x.htm#x</a> <br>
    <img alt="This image shows: junk"> <br>
    <img alt="This image shows: ">
  </body>
</html>
