<%-- generated by Dynamator Sun Feb 15 17:30:05 CST 2004
--%><html>
  <head>
    <title>Test Attribute Content</title>
  </head>
  <body>
    <p class="right" align="right">This should be right-justified.</p>
    <p class="right" align="right">This should be right-justified.</p>
    <p class="left">This should be left-justified.</p>
  </body>
</html>
