<%-- generated by Dynamator Sun Feb 15 17:30:05 CST 2004
--%><html>
  <head>
    <title>Test Discard Tag</title>
  </head>
  <body>
    discard this tag
    discard this tag
    discard this tag
    discard this tag
    discard this tag
    discard this tag
  </body>
</html>
