<%-- generated by Dynamator Sat Jan 31 14:19:52 CST 2004
--%><html>
  <head>
    <title>Test Flag Attributes</title>
  </head>
  <body>
    <form><br>
      <input type="checkbox" name="t1">Should not be checked<br>
      <input type="checkbox" name="t2" checked>Should be checked</form>
  </body>
</html>
