<%-- generated by Dynamator Sun Feb 15 17:30:06 CST 2004
--%><html>
  <head>
    <title>Test Relative Position Tags</title>
  </head>
  <body>
    <h1>Test relative position tags</h1>
<p>1a.</p>
      <p>1b.</p>
    <div class="relative"><p>2.</p>
<p>content</p>
<p>3.</p>
    </div><p>4.</p>
<p>1a.</p>
      <p>1b.</p>
<div class="relative"><p>2.</p>
<p>content 1</p>
      <p>content 2</p>
<p>3.</p>
    </div><p>4.</p>
</body>
</html>
