<!-- generated by Dynamator Sun Feb 29 00:26:17 CST 2004 -->
<xsl:stylesheet 
    version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="xml" indent="yes"/>

<!-- identity transform -->
<xsl:template match="@*|node()">
  <xsl:copy>
    <xsl:apply-templates select="@*|node()"/>
  </xsl:copy>
</xsl:template>

<xsl:template match="/faq">
<html>
  <head>
    <title>Dynamator: FAQ</title>
    <link type="text/css" href="style.css" rel="stylesheet"></link>
    <style type="text/css">
          br { padding-top: 0px; padding-bottom: 0px; margin-top: 0px; margin-bottom: 0px; }
          h2 { padding-bottom: 10px; }
          .question { font-weight: bold; }
          #faq tr td { padding-right: 5px; }
    </style>
  </head>
  <body>
    <h1>Frequently Asked Questions</h1>
    <!-- don't know how to do this without a table :-( -->
    <table id="faq" border="0" cellpadding="0" cellspacing="0" summary="" width="100%">
      <xsl:for-each select="section">
        <tr><td colspan="2"><br></br>
            <b class="section-name"><xsl:value-of select="@name"/></b></td></tr>
        <xsl:for-each select="q">
          <tr class="dyn-entry">
            <td><xsl:number count="/faq//*" level="multiple" format="1.1"/></td>
            <td>

    <xsl:variable name="href">
      <xsl:text>#</xsl:text>
      <xsl:value-of select="position()"/>
    </xsl:variable>
                <a class="question" href="{$href}"><xsl:value-of select="@name"/></a>
            </td>
          </tr>
        </xsl:for-each></xsl:for-each>
      <tr><td colspan="2"><br></br><hr></hr><br></br></td></tr>
      <xsl:for-each select="section">
        <tr><td colspan="2">
            <h2 class="section-name"><xsl:value-of select="@name"/></h2></td></tr>
        <xsl:for-each select="q">
          <tr class="dyn-entry">
            <td><xsl:number count="/faq//*" level="multiple" format="1.1"/></td>
            <td>
              <a name="{position()}" class="question"><xsl:value-of select="@name"/></a>
              <br></br>
<xsl:apply-templates select="answer/*"/>              <br></br>
            </td>
          </tr>
        </xsl:for-each></xsl:for-each>
    </table>         
  </body>
</html>

</xsl:template>

</xsl:stylesheet>
