<%-- generated by Dynamator Thu Oct 10 16:40:07 CDT 2002
--%>
<%@ page import="java.util.Dictionary"%>
<%@ page import="java.util.Enumeration"%>
<%@ page import="java.util.Hashtable"%>
<%@ page session="false" %>
<%!
    private 
    Dictionary 
    obtainRequestArguments_(
        ServletRequest request
        )
    {
        Dictionary result = new Hashtable();
        String name;
        Enumeration e = request.getParameterNames();
        while ( e.hasMoreElements() )
        {
            name = e.nextElement().toString();
            result.put(name, request.getParameter(name));
        }
        return result;
    }

    private 
    Dictionary 
    obtainRequestHeaders_(
        HttpServletRequest request
        )
    {
        Dictionary result = new Hashtable();
        String name;
        Enumeration e = request.getHeaderNames();
        while ( e.hasMoreElements() )
        {
            name = e.nextElement().toString();
            result.put(name, request.getHeader(name));
        }
        return result;
    }


    private 
    Dictionary 
    obtainSessionData_(
        HttpSession session
        )
    {
        Dictionary result = new Hashtable();
        String[] names = session.getValueNames();
        int i = names.length;
        while ( --i >= 0 )
        {
            result.put(names[i], session.getValue(names[i]));
        }
        return result;
    }
%>
<%
    Dictionary requestArguments = obtainRequestArguments_(request);
    Dictionary requestHeaders   = obtainRequestHeaders_(request);
    HttpSession session         = request.getSession(false);
    Dictionary sessionData = 
        session == null 
        ? null
        : obtainSessionData_(session);
%>
<html>
  <head>
    <title>Information available to this Servlet</title>
  </head>
  <body>
    <p>The class name of this servlet is <b><span id="classname"><%= this.getClass().getName() %></span></b>.</p>
    <p>The name of the thread supporting this servlet invocation: <b><span id="threadname"><%= Thread.currentThread().getName() %></span></b>.</p>
    <p>Free memory available to the Java Virtual Machine: <b><span id="freememory"><%= Runtime.getRuntime().freeMemory() %></span></b>.</p>
    <p>Total memory available to the Java Virtual Machine: <b><span id="totalmemory"><%= Runtime.getRuntime().totalMemory() %></span></b>.</p>
    <h1>Request Arguments</h1>
    <table border="1">
<%
        {
          java.util.Dictionary $requestArguments = requestArguments;
          String argument;
          String argumentKey;
          java.util.Enumeration $requestArgumentsKeys = $requestArguments.keys();
          while ( $requestArgumentsKeys.hasMoreElements() )
          {
            argumentKey = (String) $requestArgumentsKeys.nextElement();
            argument = (String) $requestArguments.get(argumentKey);
      %>
            <tr id="RequestArguments">
              <td id="RequestArgumentName"><%= argumentKey %></td>
              <td id="RequestArgumentValue"><%= argument %></td>
            </tr><%
          }
        }
      %>
    </table>
    <p><span id="NumberOfRequestArguments"><%= requestArguments.size() %></span> arguments were sent to this servlet.</p>
    <h1>Request Information</h1>
    <table border="1">
      <tr>
        <td>authType</td>
        <td id="AuthType"><%= request.getAuthType() %></td>
      </tr>
      <tr>
        <td>characterEncoding</td>
        <td id="CharacterEncoding"><%= request.getCharacterEncoding() %></td>
      </tr>
      <tr>
        <td>contentLength</td>
        <td id="ContentLength"><%= request.getContentLength() %></td>
      </tr>
      <tr>
        <td>contentType</td>
        <td id="ContentType"><%= request.getContentType() %></td>
      </tr>
      <tr>
        <td>method</td>
        <td id="Method"><%= request.getMethod() %></td>
      </tr>
      <tr>
        <td>pathInfo</td>
        <td id="PathInfo"><%= request.getPathInfo() %></td>
      </tr>
      <tr>
        <td>pathTranslated</td>
        <td id="PathTranslated"><%= request.getPathTranslated() %></td>
      </tr>
      <tr>
        <td>protocol</td>
        <td id="Protocol"><%= request.getProtocol() %></td>
      </tr>
      <tr>
        <td>queryString</td>
        <td id="QueryString"><%= request.getQueryString() %></td>
      </tr>
      <tr>
        <td>remoteAddr</td>
        <td id="RemoteAddr"><%= request.getRemoteAddr() %></td>
      </tr>
      <tr>
        <td>remoteHost</td>
        <td id="RemoteHost"><%= request.getRemoteHost() %></td>
      </tr>
      <tr>
        <td>remoteUser</td>
        <td id="RemoteUser"><%= request.getRemoteUser() %></td>
      </tr>
      <tr>
        <td>requestURI</td>
        <td id="RequestURI"><%= request.getRequestURI() %></td>
      </tr>
      <tr>
        <td>requestedSessionId</td>
        <td id="RequestedSessionId"><%= request.getRequestedSessionId() %></td>
      </tr>
      <tr>
        <td>scheme</td>
        <td id="Scheme"><%= request.getScheme() %></td>
      </tr>
      <tr>
        <td>serverName</td>
        <td id="ServerName"><%= request.getServerName() %></td>
      </tr>
      <tr>
        <td>serverPort</td>
        <td id="ServerPort"><%= request.getServerPort() %></td>
      </tr>
      <tr>
        <td>servletPath</td>
        <td id="ServletPath"><%= request.getServletPath() %></td>
      </tr>
    </table>
    <h1>Request Headers</h1>
    <p>obtained using request.getHeader(<i>name</i>)</p>
    <table border="1">
<%
        {
          java.util.Dictionary $requestHeaders = requestHeaders;
          String header;
          String headerKey;
          java.util.Enumeration $requestHeadersKeys = $requestHeaders.keys();
          while ( $requestHeadersKeys.hasMoreElements() )
          {
            headerKey = (String) $requestHeadersKeys.nextElement();
            header = (String) $requestHeaders.get(headerKey);
      %>
            <tr id="Headers">
              <td id="HeaderName"><%= headerKey %></td>
              <td id="HeaderValue"><%= header %></td>
            </tr><%
          }
        }
      %>
    </table>
    <h1>Session Properties</h1>
<%
      if ( session != null ) 
      {
        %>
        <div id="IfWithinSession">
          <p>obtained using session.getValue(<i>name</i>)</p>
          <table border="1">
<%
              {
                java.util.Dictionary $sessionData = sessionData;
                Object value;
                String valueKey;
                java.util.Enumeration $sessionDataKeys = $sessionData.keys();
                while ( $sessionDataKeys.hasMoreElements() )
                {
                  valueKey = (String) $sessionDataKeys.nextElement();
                  value = (Object) $sessionData.get(valueKey);
            %>
                  <tr id="SessionVariables">
                    <td id="SessionVariableName"><%= valueKey %></td>
                    <td id="SessionVariableValue"><%= value %></td>
                  </tr><%
                }
              }
            %>
          </table>
        </div><%
      }
    %>
<%
      if ( session == null ) 
      {
        %>
        <div id="IfNotWithinSession">
          <p>(No session available)</p>
        </div><%
      }
    %>
  </body>
</html>
