<%-- generated by Dynamator Thu Oct 10 16:40:07 CDT 2002
--%>
<%@ page import="java.util.Vector"%>
<%@ page session="true" %>
<%
    Vector history = (Vector) session.getValue("history");
    if ( history == null )
    {
        history = new Vector();
        session.putValue("history", history);
    }
    String textInput = request.getParameter("TextInput");
    if ( textInput == null )
    {
        textInput = "";
    }
    history.addElement(textInput);
%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Dynamator Enhanced Text Echo Example</title>
  </head>
  <body>
    <form action="<%= response.encodeURL(request.getServletPath()) %>" method="GET">
      <center>
        <table align="center">
<%
            {
              java.util.Vector $history = history;
              int lim$history = $history.size();
              String item;
              for ( int iItem = 0; iItem < lim$history; ++iItem )
              {
                item = (String) $history.elementAt(iItem);
          %>
                <tr class="HistoryRow">
                  <td>
                    <pre>
<%= item %>
</pre>
                  </td>
                </tr><%
              }
            }
          %>
          <tr>
            <td>
              <hr>
            </td>
          </tr>
          <tr>
            <td>New text: <input size="50" value="<%= textInput %>" maxlength="500" id="TextInputField" type="TEXT" name="TextInput"> </td>
          </tr>
        </table>
        <input value="Display Text" type="SUBMIT">
      </center>
    </form>
  </body>
</html>
