<?xml version="1.0"?>
<xsl:stylesheet
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	version="1.0" >

<xsl:output method="html"/>
<html>
  <head>
    <title>Font sizes</title>
  </head>
  <body>
    <xsl:for-each select="//size">
      <p><font size="{.}">This is font size <xsl:value-of select="."/>.</font></p>
    </xsl:for-each>
  </body>
</html>

</xsl:template>
</xsl:stylesheet>
<!-- generated by Dynamator Mon Mar 29 22:38:42 CST 2004 -->
