<?xml version="1.0"?>
<xsl:stylesheet
   xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
   version="1.0">

<xsl:template match="poem">
<!-- Modified from Michael Kay's XSLT Programmer's Reference --><html>
  <head>
    <title><xsl:value-of select="//title"/></title>
  </head>
  <body>
    <div align="center">
      <h1><xsl:value-of select="//title"/></h1>
    </div>
    <div align="center">
      <h2>By <xsl:value-of select="//author"/></h2>
    </div>
    <xsl:for-each select="stanza">
      <p>
        <xsl:for-each select="line"><xsl:value-of select="."/>
          <br>
        </xsl:for-each>
      </p>
    </xsl:for-each>
    <p><i><xsl:value-of select="//date"/></i></p>
  </body>
</html>

</xsl:template>
</xsl:stylesheet>
<!-- generated by Dynamator Mon Mar 29 22:38:44 CST 2004 -->
