<?xml version="1.0"?>
<xsl:stylesheet
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	version="1.0" >

<xsl:template match="/">
<html>
  <head>
    <title>Dynamator Glossary</title>
  </head>
  <body>
    <table>
      <tr>
        <td>Term</td>
        <td>Definition</td>
      </tr>
      <xsl:for-each select="//term">
        <tr class="entry">
          <td class="term"><xsl:value-of select="name"/></td>
          <td class="definition"><xsl:value-of select="def"/></td>
        </tr>
      </xsl:for-each>
    </table>
  </body>
</html>

</xsl:template>
</xsl:stylesheet>
<!-- generated by Dynamator Mon Mar 29 22:38:47 CST 2004 -->
