<?xml version="1.0"?>
<xsl:stylesheet
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	version="1.0" >

<xsl:template match="/">
<html>
  <head>
    <title>Dynamator Glossary</title>
  </head>
  <body>
    <dl class="entry">
      <xsl:for-each select="//term">
        <dt class="term"><xsl:value-of select="name"/></dt>
        <dd class="definition"><xsl:value-of select="def"/></dd>
      </xsl:for-each>
    </dl>
  </body>
</html>

</xsl:template>
</xsl:stylesheet>
<!-- generated by Dynamator Mon Mar 29 22:38:46 CST 2004 -->
