// generated by Dynamator Tue Jan 20 14:44:12 CST 2004

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.http.*;

public class DirectAccess
extends HttpServlet
{
    private String getGreeting()
    {
        return "Hello World, says Dynamator!";
    }

    public 
    void
    doGet(
        HttpServletRequest request,
        HttpServletResponse response
        )
    throws IOException
    {
        PrintWriter out = response.getWriter();
        response.setContentType("text/html");

        String countArgument = request.getParameter("count");
        int count = 
            ( countArgument == null || countArgument.length() == 0 )
            ? 5
            : Integer.parseInt(countArgument);
        out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
        out.write("<html>\n");
        out.write("  <head>\n");
        out.write("    <title>");
            out.write(String.valueOf(( count == 0 ) 
                  ? getGreeting()
                  : String.valueOf(count)));
            out.write("</title>\n");
        if ( count > 0 ) 
        {
            out.write("    <meta http-equiv=\"Refresh\" content=\"");
                out.write(String.valueOf("1; URL=" + request.getRequestURI() + "?count=" + (count-1)));
                out.write("\">");
        }
        out.write("</head>\n");
        out.write("  <body>\n");
        out.write("    <p align=\"center\"><font class=\"DynamicText\" size=\"+3\">");
            out.write(String.valueOf(( count == 0 ) 
                  ? getGreeting()
                  : String.valueOf(count)));
            out.write("</font></p>\n");
        out.write("  </body>\n");
        out.write("</html>\n");

        out.flush();
        out.close();
    }
}
