// generated by Dynamator Tue Jan 20 14:44:13 CST 2004

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.http.*;

public class HelloWorld
extends HttpServlet
{
    private String getGreeting()
    {
        return "Hello World, says Dynamator!";
    }

    public 
    void
    doGet(
        HttpServletRequest request,
        HttpServletResponse response
        )
    throws IOException
    {
        PrintWriter out = response.getWriter();
        response.setContentType("text/html");
        out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
        out.write("<html>\n");
        out.write("  <head>\n");
        out.write("    <title>Hello World</title>\n");
        out.write("  </head>\n");
        out.write("  <body>\n");
        out.write("    <p id=\"DynamicText\">");
            out.write(String.valueOf(getGreeting()));
            out.write("</p>\n");
        out.write("  </body>\n");
        out.write("</html>\n");

        out.flush();
        out.close();
    }
}
