// generated by Dynamator Tue Jan 20 14:44:13 CST 2004

import java.io.IOException;
import java.io.PrintWriter;
import java.util.*;
import javax.servlet.http.*;

public class ShoppingList
extends HttpServlet
{
    private static final String[] dinner_ = 
        new String[]
        {
            "quiche",
            "salad"
        };
    private static final Vector dessert_ = new Vector();
    static
    {
        dessert_.addElement("Pie");
        dessert_.addElement("Ice Cream");
    }

    private static final Vector reminder_ = new Vector();
    static
    {
        reminder_.addElement("Flowers");
    }

    private Enumeration reminder()
    {
        return reminder_.elements();
    }

    public 
    void
    doGet(
        HttpServletRequest request,
        HttpServletResponse response
        )
    throws IOException
    {
        PrintWriter out = response.getWriter();
        response.setContentType("text/html");
        out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
        out.write("<html>\n");
        out.write("  <head>\n");
        out.write("    <title>Shopping List</title>\n");
        out.write("  </head>\n");
        out.write("  <body>\n");
        out.write("    <p>Be sure to pick up the following items on the way home:</p>\n");
        out.write("    <ul>\n");
        {
            final String[] $dinner_ = dinner_;
            final int lim$dinner_ = $dinner_.length;
            String menuItem;
            for ( int i$dinner_ = 0; i$dinner_ < lim$dinner_; ++i$dinner_ )
            {
                menuItem = $dinner_[i$dinner_];
                out.write("      <li id=\"dinner\">");
                    out.write(String.valueOf(menuItem));
                    out.write("</li>\n");

            }
        }
        out.write("    </ul>\n");
        out.write("    <p>If you'd like dessert, please also buy:</p>\n");
        out.write("    <ul>\n");
        {
            final java.util.Vector $dessert_ = dessert_;
            final int lim$dessert_ = $dessert_.size();
            String dessertItem;
            for ( int i$dessert_ = 0; i$dessert_ < lim$dessert_; ++i$dessert_ )
            {
                dessertItem = (String) $dessert_.elementAt(i$dessert_);
                out.write("      <li id=\"dessert\">");
                    out.write(String.valueOf(dessertItem));
                    out.write("</li>\n");

            }
        }
        out.write("    </ul>\n");
        out.write("    <p>And don't forget:</p>\n");
        out.write("    <ul>\n");
        {
            final java.util.Enumeration $reminder = reminder();
            String reminderItem;
            while ( $reminder.hasMoreElements() )
            {
                reminderItem = (String) $reminder.nextElement();
                out.write("      <li id=\"reminder\">");
                    out.write(String.valueOf(reminderItem + "!"));
                    out.write("</li>\n");

            }
        }
        out.write("    </ul>\n");
        out.write("  </body>\n");
        out.write("</html>\n");

        out.flush();
        out.close();
    }
}
