// generated by Dynamator Mon Mar 29 22:08:54 CST 2004

import java.io.PrintWriter;
public
class Taxonomy_External_TreeWriter
{
    public static
    void
    printChildren(
        PrintWriter out,
        Taxonomy_External.Element element
        )
    {
            out.write("<ul class=\"children-list\">\n");
        {
            final Taxonomy_External.Element[] $elementChildren = element.children();
            final int lim$elementChildren = $elementChildren.length;
            Taxonomy_External.Element child;
            for ( int i$elementChildren = 0; i$elementChildren < lim$elementChildren; ++i$elementChildren )
            {
                child = $elementChildren[i$elementChildren];
                out.write("      <li class=\"child\"><span class=\"child-name\">");
                    out.write(String.valueOf(child.name()));
                    out.write("</span> \n");

      if ( child.children().length > 0 )
      {
          printChildren(out, child);
      }
                    out.write("      </li>\n");

            }
        }
        out.write("    </ul>");

    }
}
    