// generated by Dynamator Sat Jan 31 14:47:56 CST 2004

import java.io.IOException;
import java.io.PrintWriter;
import java.util.*;
import javax.servlet.http.*;

public class TextEcho
extends HttpServlet
{
    public 
    void
    doGet(
        HttpServletRequest request,
        HttpServletResponse response
        )
    throws IOException
    {
        PrintWriter out = response.getWriter();
        response.setContentType("text/html");

        String textInput = request.getParameter("TextInput");
        if ( textInput == null )
        {
            textInput = "";
        }
        out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
        out.write("<html>\n");
        out.write("  <head>\n");
        out.write("    <title>Dynamator Text Echo Example</title>\n");
        out.write("  </head>\n");
        out.write("  <body>\n");
        out.write("    <hr>\n");
        out.write("    <form method=\"GET\">\n");
        out.write("      <center>\n");
        out.write("        <p>Enter text here: <input type=\"TEXT\" name=\"TextInput\" id=\"TextInputField\" value=\"");
            out.write(String.valueOf(textInput));
            out.write("\" maxlength=\"500\" size=\"50\"></p>\n");
        out.write("        <input type=\"SUBMIT\" value=\"Display Text\"> \n");
        out.write("        <hr>\n");
        out.write("        <b id=\"TextInputDisplay\">");
            out.write(String.valueOf(textInput));
            out.write("</b>");
        out.write("</center>\n");
        out.write("    </form>\n");
        out.write("  </body>\n");
        out.write("</html>\n");

        out.flush();
        out.close();
    }
}
