// generated by Dynamator Sat Jan 31 14:47:56 CST 2004

import java.io.IOException;
import java.io.PrintWriter;
import java.util.*;
import javax.servlet.http.*;

public class TextEcho2
extends HttpServlet
{
    public 
    void
    doGet(
        HttpServletRequest request,
        HttpServletResponse response
        )
    throws IOException
    {
        PrintWriter out = response.getWriter();
        response.setContentType("text/html");

        String textInput = request.getParameter("TextInput");
        if ( textInput == null )
        {
            textInput = "";
        }
        out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
        out.write("<html>\n");
        out.write("  <head>\n");
        out.write("    <title>Dynamator Enhanced Text Echo Example</title>\n");
        out.write("    <script type=\"text/javascript\">\n");
        out.write("    var previousValue = \"");
            out.write(String.valueOf(textInput));
            out.write("\";\n");
        out.write("    function validate(form)\n");
        out.write("    {\n");
        out.write("        if ( form.elements[\"TextInput\"].value == previousValue )\n");
        out.write("        {\n");
        out.write("            alert(\"You just entered that value. \"\n");
        out.write("                + \"Please try to be more creative.\");\n");
        out.write("            return false;\n");
        out.write("        }\n");
        out.write("        return true;\n");
        out.write("    }\n");
        out.write("  \n");
        out.write("</script>\n");
        out.write("  </head>\n");
        out.write("  <body>\n");
        out.write("    <hr>\n");
        out.write("    <form method=\"GET\">\n");
        out.write("      <center>\n");
        out.write("        <p>Please enter some new text: <input type=\"TEXT\" name=\"TextInput\" id=\"TextInputField\" value=\"");
            out.write(String.valueOf(textInput));
            out.write("\" maxlength=\"500\" size=\"50\"></p>\n");
        out.write("        <input type=\"SUBMIT\" value=\"Display Text\" onclick=\"validate(this.form)\"> \n");
        out.write("        <hr>\n");
        out.write("        <table>\n");
        out.write("          <tr>\n");
        out.write("            <td>\n");
        out.write("              <pre>\n");
            out.write(String.valueOf(textInput));
            out.write("\n");
        out.write("</pre>\n");
        out.write("            </td>\n");
        out.write("          </tr>\n");
        out.write("        </table>\n");
        out.write("      </center>\n");
        out.write("    </form>\n");
        out.write("  </body>\n");
        out.write("</html>\n");

    }
}
