// generated by Dynamator Sat Jan 31 14:47:56 CST 2004

import java.io.IOException;
import java.io.PrintWriter;
import java.util.*;
import javax.servlet.http.*;

public class TrueFalse
extends HttpServlet
{
    public 
    void
    doGet(
        HttpServletRequest request,
        HttpServletResponse response
        )
    throws IOException
    {
        PrintWriter out = response.getWriter();
        response.setContentType("text/html");

        String valueArgument = request.getParameter("value");
        boolean value = 
            ( valueArgument == null )
            ? false
            : Boolean.valueOf(valueArgument).booleanValue();
        out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
        out.write("<html>\n");
        out.write("  <head>\n");
        out.write("    <title>Dynamator Conditional Processing Example</title>\n");
        out.write("  </head>\n");
        out.write("  <body>\n");
        out.write("    <hr>\n");
        out.write("    <form id=\"form\" action=\"");
            out.write(String.valueOf(request.getServletPath()));
            out.write("\" method=\"GET\">\n");
        out.write("      <p>Select the value desired: <select name=\"value\">\n");
        out.write("          <option id=\"valueIsTrue\" value=\"true\"");
        if ( value ) 
        {
            out.write(" selected");
        }
        out.write(">true");
        out.write("</option>\n");
        out.write("          <option id=\"valueIsFalse\" value=\"false\"");
        if ( ! value ) 
        {
            out.write(" selected");
        }
        out.write(">false");
        out.write("</option>\n");
        out.write("        </select> <input type=\"SUBMIT\">");
        out.write("</p>\n");
        out.write("    </form>\n");
        out.write("    <hr>\n");
        if ( request.getQueryString()!=null ) 
        {
            out.write("    <div id=\"response\">\n");
            if ( value ) 
            {
                out.write("      <p id=\"trueText\">You are so optimistic!</p>");
            }
            if ( ! value ) 
            {
                out.write("<p id=\"falseText\" class=\"HideForDemo\">Don't be so negative!</p>");
            }
            out.write("</div>");
        }
        out.write("</body>\n");
        out.write("</html>\n");

        out.flush();
        out.close();
    }
}
