<?php /* generated by Dynamator Tue Apr 06 07:46:33 CDT 2004 */
?>
<?php
    $dates = array(
        "1/27"  => "Wolfgang Amadeus Mozart, 1756",
        "2/3"   => "Felix Mendelssohn, 1809",
        "2/23"  => "Georg Friedrich Handel, 1685",
        "3/21"  => "Johann Sebastian Bach, 1685",
        "3/25"  => "Bela Bartok, 1881",
        "3/31"  => "Franz Joseph Haydn, 1732",
        "4/27"  => "Sergei Prokofiev, 1891",
        "5/5"   => "Johannes Brahms, 1833",
        "6/2"   => "Sir Edward Elgar, 1857",
        "6/15"  => "Edward Grieg, 1843",
        "7/3"   => "Leos Janacek, 1854",
        "7/7"   => "Gustav Mahler, 1860",
        "8/22"  => "Claude Debussy, 1862",
        "9/4"   => "Anton Bruckner, 1824",
        "9/8"   => "Anton Dvorak, 1841",
        "9/26"  => "George Gershwin, 1898",
        "10/20" => "Charles Ives, 1874",
        "10/22" => "Franz List, 1811",
        "11/18" => "Carl Weber, 1786",
        "12/10" => "Cesar Franck, 1822",
        "12/15" => "Ludwig van Beethoven, 1770",
        "12/30" => "Dmitri Kabalevsky, 1904"
        );
    $datekeys = array_keys($dates);
    $dayNames = array("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat");
    $monthNames = array(NULL, "January", "February", "March", "April",
        "May", "June", "July", "August", "September", "October",
        "November", "December"); 
    $daysInMonth = array(NULL, 31, "?", 31, 30, 31, 30, 31, 31, 30, 31, 30, 31);

    $today = getdate();
    $thisDay = $today['mday'];
    $thisMonth = $today['mon'];
    $thisYear = $today['year'];
    if ( ! isset($month) )
    {
        $month = $thisMonth;
        $year  = $thisYear;
    }
    $monthName = $monthNames[$month];    

    /* find first day of month */
    $firstDateOfMonth = getDate(mktime(0,0,0,$month,1,$year));
    $calendarDay = 1 - $firstDateOfMonth['wday'] - 1;

    /* find last day of month */
    $lastDayOfMonth = $daysInMonth[$month];
    if ( $lastDayOfMonth == '?' )
    {
        $lastDayOfMonth = 
            ( $year%400 == 0 || ( $year%100 != 0 && $year%4 == 0  ) )
            ? 29
            : 28;
    }

    $prevMonth = $month - 1;
    $prevYear  = $year;
    if ( $prevMonth <= 0 )
    {
        $prevMonth = 12;
        --$prevYear;
    }
    
    $nextMonth = $month + 1;
    $nextYear  = $year;
    if ( $nextMonth >= 12 )
    {
        $nextMonth = 1;
        ++$nextYear;
    }
?>
<!--
    Calendar
    
    Calendar months have varying numbers of weeks and varying
    patterns of days (starting and ending on different days of the
    week).  Therefore the HTML markup for this example uses the notion
    of "prototypes".  This HTML demo page shows a single, real month.
    Out of the five weeks in the month, one week is selected as the
    prototype week.  Out of the 7 days in that week, one is selected as
    the prototype day.  This day shows all possible data that might be
    displayed for any given day.
    
    Each prototype is given an id.  The programmer instructs Dynamator
    to remove all non-prototype weeks and days, and uses the prototype
    ones to build the calendar at runtime.
--><html>
  <head>
    <title><?php echo (
    "$monthName $year"
  ) ?></title>
    <style type="text/css">
      a
      {
          text-decoration: none;
          color: #f9f9ee;
          font-weight: bold;
      }
      td
      {
          font-size: 10pt;
          font-family: sans-serif;
      }
      .month-header
      {
          background-color: #666666;
          color: #f9f9ee;
      }
      #month-title
      {
          background-color: #666666;
          color: #f9f9ee;
      }
      .day-header
      {
          background-color: #778899;
          color: #f9f9ee;
          text-align: center;
      }
      .weekday-name
      {
          background-color: #778899;
          color: #f9f9ee;
          text-align: center;
      }
      .other-month
      {
          background-color: #f9f9ee;
          width: 75px;
          height: 75px;
          vertical-align: top;
      }
      .this-month
      {
          background-color: #f0f0cc;
          width: 75px;
          height: 75px;
          vertical-align: top;
      }
      #today
      {
          background-color: #ffff99;
          height: 75px;
          vertical-align: top;
      }
      .event
      {
          font-size: 8pt;
      }
    </style>
  </head>
  <body>
    <table align="center" border="1" cellpadding="1" cellspacing="0">
      <tr class="month-header">
        <td colspan="7">
          <table border="0" width="100%">
            <tr>
              <td align="left"><a id="prev" href="<?php echo (
      $_SERVER['SCRIPT_NAME'] . "?month=$prevMonth&year=$prevYear"
    ) ?>">&#171;</a></td>
              <td id="month-title" align="center"><?php echo (
    "$monthName $year"
  ) ?></td>
              <td align="right"><a id="next" href="<?php echo (
      $_SERVER['SCRIPT_NAME'] . "?month=$nextMonth&year=$nextYear"
    ) ?>">&#187;</a></td>
            </tr>
          </table>
        </td>
      </tr>
      <tr class="day-header">
<?php 
          foreach ( $dayNames as $dayName)
          {
        ?><td class="weekday-name"><?php echo (
    $dayName
  ) ?></td><?php 
          }
      ?>
    </tr>

    <?php while ( $calendarDay < $lastDayOfMonth ) { ?>
        <tr class="week">

    <?php
        for ($dayOfWeek = 0; $dayOfWeek < 7; ++$dayOfWeek) {
            ++$calendarDay;
    ?>
          <td<?php 
          if ( $calendarDay == $thisDay && $month == $thisMonth && $year == $thisYear)
          {
            ?> id="today"<?php 
          }
        ?> class="<?php echo (
      1 <= $calendarDay && $calendarDay <= $lastDayOfMonth
        ? "this-month"
        : "other-month"
    ) ?>" height="75" width="75"><?php echo (
    1 <= $calendarDay && $calendarDay <= $lastDayOfMonth
    ? $calendarDay
    : "&nbsp;"
  ) ?>
          <p class="event"><?php echo (
    in_array("$month/$calendarDay", $datekeys) 
    ? $dates["$month/$calendarDay"] 
    : ""
  ) ?></p>
        </td>
    <?php } ?>
  </tr>
    <?php } ?>
  </table>
</body>
</html>
