<?php /* generated by Dynamator Tue Apr 06 07:29:17 CDT 2004 */
?><html>
  <head>
    <title>Font sizes</title>
  </head>
  <body>
<?php 
      for ( $i = 1; $i <= 7; $i++ )
      {
    ?>
        <p><font size="<?php echo (
        $i
      ) ?>">This is font size <?php echo (
      $i
    ) ?>.</font></p>
<?php 
      }  // for
    ?>
  </body>
</html>
