<?php /* generated by Dynamator Tue Apr 06 07:29:17 CDT 2004 */
?>
<?php 
    $greeting = "Hello World, says Dynamator!";
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Hello World</title>
  </head>
  <body>
    <p id="DynamicText"><?php echo ($greeting) ?></p>
  </body>
</html>
