<?php /* generated by Dynamator Tue Apr 06 07:29:17 CDT 2004 */
?>
<?php
    class Taxonomy
    {
        var $name;
        var $children;
        
        function Taxonomy($name, $children)
        {
            $this->name = $name;
            $this->children = $children;
        }
    }

    $taxonomy = new Taxonomy(
        "Animals",
        array(
            new Taxonomy(
                "Vertebrates",
                array(
                    new Taxonomy(
                        "Warm-blooded",
                        array(
                            new Taxonomy(
                                "Mammals",
                                null
                                ),
                            new Taxonomy(
                                "Birds",
                                null
                                )
                            )
                        ),
                    new Taxonomy(
                        "Cold-blooded",
                        array(
                            new Taxonomy(
                                "Fish",
                                null
                                ),
                            new Taxonomy(
                                "Reptiles",
                                null
                                )
                            )
                        )
                    )
                ),
            new Taxonomy(
                "Invertebrates",
                array(
                    new Taxonomy(
                        "Arthropods",
                        array(
                            new Taxonomy(
                                "Crustaceans",
                                null
                                ),
                            new Taxonomy(
                                "Insects",
                                null
                                )
                            )
                        )
                    )
                )
            )
        );
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Taxonomy</title>
  </head>
  <body>
    <h1 id="title"><?php echo (
      'An Informal Taxonomy of the Animal Kingdom'
    ) ?></h1>
    <p id="root"><?php echo ($taxonomy->name) ?></p>

      <?php
        output_children($taxonomy->children)
      ?>
    </body>
</html>

<?php
function output_children($children)
{
?>
    <?php 
      if ( $children != null)
      {
        ?><ul class="children-list">
<?php 
            foreach ( $children as $child)
            {
          ?><li class="child"><span class="child-name"><?php echo ($child->name) ?></span> 
<?php echo (
      output_children($child->children)
    ) ?>              </li><?php 
            }
        ?>
      </ul><?php 
    }
  ?>
<?php
}
?>
    