<?php /* generated by Dynamator Tue Apr 06 07:29:17 CDT 2004 */
?>
  <?php
    $terms = array(
        'epilog' => 'The end of the generated file, after the template.'
        ,
        'locator' => 'An element in a Dynamator annotations file that identifies '
            . 'the set of elements to which a set of overrides will apply.'
        ,
        'marker' => 'An invisible HTML element or attribute that identifies a '
            . 'location in an HTML file.  The HTML 4.0 markers are '
            . 'div, span, id, and class.'
        ,
        'override' => 'An element in a Dynamator annotations file that specifies '
            . 'a set of changes to be applied to the template.  '
            . '(AKA "modifier")'
        ,
        'prolog' => 'The beginning of the generated file, before the template.'
        ,
        'template' => 'The file containing the static text pattern to be output '
            . ' by the generated program. '
        );
  ?>
  <html>
  <head>
    <title>Dynamator Glossary</title>
  </head>
  <body>
    <dl class="entry"><?php 
        foreach ( $terms as $term => $def)
        {
      ?>
          <dt class="term"><?php echo (
      $term
    ) ?></dt>
          <dd class="definition"><?php echo (
      $def
    ) ?></dd>
<?php 
        }
    ?></dl>
</body>
</html>
