<?php /* generated by Dynamator Tue Apr 06 07:46:33 CDT 2004 */
?>
<?php 
    $hour = date("H"); 
    $now  = date("l d M Y H:i:s");
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>What time is it?</title>
  </head>
  <body>
    <p>The time is <span id="CurrentTime"><?php echo $now ?></span></p>
<?php 
      if ( $hour < 12)
      {
        ?><p id="IfMorning">Good Morning!</p><?php 
      }
    ?>
<?php 
      if ( 12 <= $hour && $hour < 18)
      {
        ?><p id="IfAfternoon">Good Afternoon!</p><?php 
      }
    ?>
<?php 
      if ( 18 <= $hour)
      {
        ?><p id="IfEvening">Good Evening!</p><?php 
      }
    ?>
  </body>
</html>
